### PR TITLE
Sarsalijo -Find the difference of two numbers

### PR DESCRIPTION
**Pull request by LadyMaxineSarsalijo**
# Submission

To pass your submission, simply follow the steps below:
1. Click on the `submissions.md` and click on the `✏`️ (Edit) icon.
2. Append the URL of your repository:
    ```md
    [Last Name - Problem](https://github.com/#user/repo)
    ```
3. Click on the `Commit changes...` button
4. On the commit message field, change the 'Update README.md' to `Last Name - Problem`.
5. Click on the `Propose changes` button.
6. After clicking on the `Propose changes` button, you will then be redirected to a new page. Click on the `Create pull request` button.
7. Done!

### CODE REVIEW

**Comment by egargo** [comment]
@LadyMaxineSarsalijo, I've checked your code. Please update the `min()` function, the operation was incorrect. Also, please move the `MinTestCase` class outside of the `min()` function. Thank you.

**Comment by egargo** [comment]
@LadyMaxineSarsalijo, isa nalang error sa line [14](https://github.com/LadyMaxineSarsalijo/Sarsalijo_UnitTesting/blob/main/main.py#L14). Paki change lang ang expected value to `5` instead of `-10`. Thank you.

**Comment by LadyMaxineSarsalijo** [comment]
@egargo inani? or apilon ning isa ka -10?

def test_negative_numbers(self):
        result = min(-5, -10)
        self.assertEqual(result, 5)

**Comment by egargo** [comment]
@LadyMaxineSarsalijo, LGTM!

**Pull request merged**
